### ISSUE TITLE
Work through git/github tutorials

### ISSUE THREAD

**Issue by parejkoj** [UWMRO/Focuser#2]
Work through the following tutorials. You can post here with questions and I'll answer on this Issue, if you want to keep a record for the future.

This one is really good to learn what all these words and commands mean. Work through the first 2 Introduction Sequence steps here: https://learngitbranching.js.org/

Do the "basics of github course" here: https://lab.github.com/

**Comment by parejkoj** [comment]
Status check: how are the tutorials going?

**Comment by maria8ch** [comment]
Did the whole intro sequence of the branching one, which course is the basics one? Is it the first week on github one?

**Comment by parejkoj** [comment]
After you've finished the "Basics of Github" on the Learning Lab, you could follow up with the "First Day" tutorial on the same page. I wouldn't bother with the "First Week" one, at least for now.

**Comment by darrenhunt2** [comment]
Update: Finished the "Basics of GitHub" course along with learn git branching.

**Comment by maria8ch** [comment]
Update- closed the pull request thingie due to getting through that part of the GitHub tutorial.

**Comment by parejkoj** [comment]
Tutorials finished.
