### ISSUE TITLE
Create a Page describing the basic plan for focusing

### ISSUE THREAD

**Issue by parejkoj** [UWMRO/Focuser#4]
Starting from the notes we sketched out a few weeks ago, we should make a basic github Page describing our plans for focusing at MRO. We can use that to figure out what steps we need to do (as github Issues themselves), and it will serve as useful documentation for future developers and users.

Completion of this Issue will be a publicly-visible github Page with the basic plan that we original sketched out. We can flesh it out in detail later.

For now, put everything on `docs/index.md`. If we want to split up the page later, we can.

Please also add a link to https://uwmro.github.io/Focuser/ from the main `README.md`.

**Comment by parejkoj** [comment]
A short guide to writing markdown:

https://www.markdownguide.org/basic-syntax

**Comment by darrenhunt2** [comment]
Just reviewed.

**Comment by parejkoj** [comment]
Closing: #5 takes care of this.
